name: Generate GitBlog Index

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:
    branches:
      - master
    paths:
      - main.py

env:
  GITHUB_NAME: drunkwretch 
  GITHUB_EMAIL: drunkwretch@gmail.com

jobs:
  sync:
    name: Generate index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Configure pip cache
        uses: actions/cache@v1
        id: pip-cache
        with:
          path: venv
          key: pip-1-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
        if: steps.pip-cache.outputs.cache-hit != 'true'

      - name: Generate new md
        run: |
          source venv/bin/activate
          python main.py ${{ secrets.GITBLOG }} ${{ github.repository }} --issue_numbe '${{ github.event.issue.number }}'

      - name: Push index 
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITBLOG }}
          commit-message: "Refresh index AND BACK UP"
          files: README.md index.html BACKUP/
          rebase: 'true'
          name: ${{ env.GITHUB_NAME }}
          email: ${{ env.GITHUB_EMAIL }}
